### ISSUE TITLE
BarcelonaJS 2.0 (website)

### ISSUE THREAD

**Issue by lluia** [BarcelonaJS/barcelonajs.github.io#23]
I'm opening this issue as a place to **discuss**, **track** and **suggest** work related to the new _BarcelonaJS_ website we plan to build.

## 👨‍👨‍👧‍👧 Collaborators

- @Gpx 
- Marce Ramirez
- @lluia
- @onedesert 
- Kama
- Iago Lastra ?
- ... ( _add more as they show interest_ )

## ✍🏻 &nbsp;Planning

Would be good to [create a board](https://help.github.com/articles/about-project-boards/) ( @Gpx 🙏🏻  ) to gain:
- [ ] 👀 overview of the work lying ahead ( _making sure we don't miss anything_ )
- [ ] 🏋️  overview of the progress being done
- [ ] 🤦🏻‍♂️ visibility when splitting and assigning work ( _so we don't step on each other_ )

I'm happy to step up as a mantainer of the board and the issues we open to track work.  

## 🥤 Todos

_**I'll move this to issues and a board once we make it_ 👍🏻

#### 1. Propose initial design mockup/s ( Kama ) 
- [idea 1](https://meetup.react.london/) ( _London React Meetup site_ )
- [idea 2](https://generalassemb.ly/education/programming-for-non-programmers-bootcamp/london/56005) ( _General Assembly London workshop page_ )
#### 2. Propose logo re-design ( Kama )
- current design doesn't say Barcelona
- current design might be a bit dark
#### 3. Agree on new content ( Iago Lastra, @Gpx  ? )
- [bare minimum we need](https://barcelonajs.slack.com/archives/GDMDX2CTT/p1540544816002700)
- start simple? ( `home | next event info | contact` )
#### 4. Setup development branch ( @lluia )
- so we can open PRs against and review each other code
- I have this locally, just need push rights
#### 5. Setup [GatsbyJS starter](https://www.gatsbyjs.org/docs/) ( @lluia )
- I have this locally, just need push rights to open a PR
- we can discuss tooling on the PR
#### 6. Query events data from [Meetup API](https://www.meetup.com/meetup_api/) 
- can be done without waiting for designs
- I believe the API should be friendly enough ( 🤞🏻 )
